INSERT INTO user( id, dtype,last_name, name,password,role,user_name,jmbg,address,date_of_birth,gender,picture_path) VALUES ( '1','Student', 'peric', 'pera', "$2a$10$KVlDpMjpRVu8WiMQrttt4.epl6aBcI0V9BlwUxzEakFrCEaGVrQ7C", 'STUDENT', 'student', '23525235235233', 'da', '2008-10-03 22:59:52', 'male', 'da');
INSERT INTO user( id, dtype,last_name, name,password,role,user_name) VALUES ( '3','User', 'dali', 'dali', "$2a$10$KVlDpMjpRVu8WiMQrttt4.epl6aBcI0V9BlwUxzEakFrCEaGVrQ7C", 'ADMIN', 'admin');
INSERT INTO user(id, dtype ,last_name, name,password,role,user_name,jmbg,address,date_of_birth,gender,picture_path,title) VALUES ( '2','Professor',  'jovo', 'jovic', "$2a$10$KVlDpMjpRVu8WiMQrttt4.epl6aBcI0V9BlwUxzEakFrCEaGVrQ7C", 'PROFESSOR', 'profesor', '1313121251251', 'da', '2008-10-03 22:59:52', 'male', 'da', 'da');
INSERT INTO transaction (id, bank_account,price, purpose, recipient, student_id) VALUES ('1', '2222222', '2000', 'dada', 'dede', '1');
INSERT INTO document (id, name, path,student_id) VALUES ('1', 'indeks', 'aha', '1');
INSERT INTO subject (id,name,semester) VALUES ('1', 'Engleski', '1');
INSERT INTO exam (id,pass,points,student_id,subject_id) VALUES ('1', true, '90', '1','1');
INSERT INTO obligation(id,date_of_obligation,obligation_type,points,subject_id) VALUES ('1', '2008-10-03 22:59:52', 'kolokvijum', '30', '1');
INSERT INTO professor_role(id,role,professor_id,subject_id) VALUES ('1', 'rola', '2', '1');
INSERT INTO user_subjects (students_id,subjects_id) VALUES ('1', '1');
